### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by johanneswuerbach** [Automattic/engine.io-parser#39]
engine.io-parser includes various fixes since the last release https://github.com/Automattic/engine.io-parser/compare/1.1.0...master (I need the PhantomJS fixes) Is there a chance to get an updated version published to npm?

**Comment by defunctzombie** [comment]
cc @rase-

**Comment by defunctzombie** [comment]
released 1.2.0

**Comment by johanneswuerbach** [comment]
Thank you :+1:
