### ISSUE TITLE
Parser broken on Android 3.*

### ISSUE THREAD

**Issue by kokarn** [Automattic/engine.io-parser#40]
Hello!

I've encountered a pretty weird issue for Android Honeycomb.

The problem comes from the fact that there is specific handling for "android" devices as per [this article](https://ghinda.net/article/jpeg-blob-ajax-android/). 

It assumes that "android" can handle sending things as ArrayBuffer [in here](https://github.com/Automattic/engine.io-parser/blob/master/lib/browser.js#L168) however this only works on android >= 4. 

The check that is done for "Android" [here](https://github.com/Automattic/engine.io-parser/blob/master/lib/browser.js#L27) works for 2.* because those versions doesn't identify as "Android" but the 3.* versions does.
The problem then arises [here](https://github.com/Automattic/engine.io-parser/blob/master/lib/browser.js#L432) because [Uint8Array isn't available until Android 4](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).

I'm currently testing on a Samsung Galaxy Tab 7.7 on Android 3.2 and will try to find some way to either fix this or work around it.

**Comment by defunctzombie** [comment]
Once you do find a fix, we should write a failing test and make sure we update zuul.yml to run these older android version.

**Comment by rase-** [comment]
@kokarn hmm, I believe 3.x should have "Android" in the agent as well. Do you have an example user agent string to paste here for refence?

**Comment by kokarn** [comment]
@rase- Yes it does, that's the problem. Sorry if I was unclear.

The problem arises AFAIK from the fact that when the "Android" string is present it tries to use methods only available on Android >= 4.*

**Comment by kokarn** [comment]
So after banging my head against the wall trying to debug and patch I noticed the version in this repo is not the one in socket.io.

After updating and re-compiling it now works as intended. 
I have no clue what change actually fixed this but I'm sorry to have wasted your time.

Thanks for quick support. <3

**Comment by rase-** [comment]
Thanks for checking! :)
